var utamaVideo = [
'<iframe width="560" height="315" src="https://www.youtube.com/embed/XVTPhCDWDFk?si=UAEY5A3kVWHbr4il" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/AQjy02s4h60?si=MG2q1YfuSZPGAYsm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/L6EA0v1P07Y?si=2Wpb288hmFhm22Wu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/L3vYEOANFtE?si=6huBiH9I0WtQfuov" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/OEvqNi6O5dM?si=K2mO-Ulff7FtpbcF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/bPp4ruz6G80?si=ipTgtVFyyT96zfWx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/DliD_yFTtnM?si=DTv4fWo4KCsZB8xX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/amnDM7X2iJg?si=IUCfNixFUzWtbAd4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/WqQI7fACiWs?si=FkFSjgIBzfQzx0yd" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/bvi9Yijrd8Q?si=oH0tmnojAKwHCMK7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/-fBcGtkAy9g?si=f-HHYwzwzUsDZDpP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/_mEe4brTKMQ?si=Mq3AmnQpvPFBvkPj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
'<iframe width="560" height="315" src="https://www.youtube.com/embed/wBXVbfZnddw?si=-nEIQv0xda3aJfXW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'
];